[Appearance]
color_scheme_path=@CONFIG_HOME@/qt6ct/colors/noctalia.conf
custom_palette=true
icon_theme=Papirus-Dark
standard_dialogs=default
style=Fusion

[Fonts]
fixed="FantasqueSansM Nerd Font,12,-1,5,50,0,0,0,0,0"
general="Noto Sans,10,-1,5,50,0,0,0,0,0"
